### ISSUE TITLE
After submitting a new link, the form should clear itself and should not show old submission

### ISSUE THREAD

**Issue by avinassh** [anirudhvarma12/refeed#2]
When I submit, I do get `Message: Success`, however form still has old content. Example: 

![screen shot 2016-03-14 at 8 26 56 am](https://cloud.githubusercontent.com/assets/640792/13733918/8eafd674-e9be-11e5-843b-a18fd6cc8b55.png)

**Comment by avinassh** [comment]
Saar pliss do something about this

**Comment by anirudhvarma12** [comment]
To be honest, I looked for a solution and did not get any. There was one method which recommended refreshing the page, but then I was not able to show the message :(
